from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import mannwhitneyu


GEOMETRY_PATHS = {
    "C1": Path(
        "analysis/scc_bcc/c1_lesion_geometry/"
        "scc_lesion_geometry.csv"
    ),
    "F1": Path(
        "analysis/scc_bcc/f1/"
        "scc_lesion_geometry.csv"
    ),
}

METADATA_PATH = Path(
    "data/raw/pad_ufes/metadata.csv"
)

OUTPUT_DIR = Path(
    "analysis/scc_bcc/hurt_size_geometry"
)


REQUIRED_GEOMETRY_COLUMNS = {
    "patient_id",
    "lesion_uid",
    "scc_to_bcc_error_images",
    "error_fraction",
    "bcc_minus_scc_distance",
}

REQUIRED_METADATA_COLUMNS = {
    "patient_id",
    "lesion_id",
    "diameter_1",
    "diameter_2",
    "hurt",
}


def normalize_lesion_id(value):
    return str(value).strip()


def parse_lesion_uid(value):
    """
    PAT_492__937 -> PAT_492 / 937
    """
    value = str(value)

    if "__" not in value:
        raise RuntimeError(
            f"Unexpected lesion_uid format: {value}"
        )

    patient_id, lesion_id = value.split(
        "__",
        1,
    )

    return (
        patient_id,
        normalize_lesion_id(lesion_id),
    )


def normalize_bool(series):
    return (
        series
        .astype(str)
        .str.strip()
        .str.lower()
        .map(
            {
                "true": True,
                "false": False,
                "1": True,
                "0": False,
            }
        )
    )


def load_geometry(
    path: Path,
    label: str,
):
    if not path.exists():
        raise RuntimeError(
            f"{label} geometry file does not exist: "
            f"{path}"
        )

    df = pd.read_csv(path)

    # F1 geometry may have been generated by the
    # legacy lesion-geometry script, which used the
    # name "scc_advantage_over_bcc".
    #
    # The value has the same mathematical meaning:
    #
    #     BCC distance - SCC distance
    #
    # Positive = closer to BCC
    # Negative = closer to SCC
    if (
        "bcc_minus_scc_distance" not in df.columns
        and "scc_advantage_over_bcc" in df.columns
    ):
        df = df.rename(
            columns={
                "scc_advantage_over_bcc":
                "bcc_minus_scc_distance"
            }
        )

    missing = sorted(
        REQUIRED_GEOMETRY_COLUMNS
        - set(df.columns)
    )

    if missing:
        raise RuntimeError(
            f"{label} geometry missing columns: "
            f"{missing}"
        )

    df = df.copy()

    df["lesion_uid"] = (
        df["lesion_uid"]
        .astype(str)
        .str.strip()
    )

    parsed = df["lesion_uid"].apply(
        parse_lesion_uid
    )

    df["patient_id_from_uid"] = (
        parsed.apply(lambda x: x[0])
    )

    df["lesion_id_key"] = (
        parsed.apply(lambda x: x[1])
    )

    if not (
        df["patient_id"].astype(str)
        == df["patient_id_from_uid"].astype(str)
    ).all():
        raise RuntimeError(
            f"{label}: patient_id does not agree "
            "with lesion_uid."
        )

    df = df.drop(
        columns="patient_id_from_uid"
    )

    if df["lesion_uid"].duplicated().any():
        duplicates = df[
            df["lesion_uid"].duplicated(
                keep=False
            )
        ]

        raise RuntimeError(
            f"{label}: duplicate lesion_uids:\n"
            + duplicates[
                ["patient_id", "lesion_uid"]
            ].to_string(index=False)
        )

    return df


def load_metadata():
    if not METADATA_PATH.exists():
        raise RuntimeError(
            f"Metadata does not exist: "
            f"{METADATA_PATH}"
        )

    metadata = pd.read_csv(
        METADATA_PATH
    )

    missing = sorted(
        REQUIRED_METADATA_COLUMNS
        - set(metadata.columns)
    )

    if missing:
        raise RuntimeError(
            f"Metadata missing columns: {missing}"
        )

    metadata = metadata.copy()

    metadata["patient_id"] = (
        metadata["patient_id"]
        .astype(str)
        .str.strip()
    )

    metadata["lesion_id_key"] = (
        metadata["lesion_id"]
        .astype(str)
        .str.strip()
    )

    metadata["diameter_1"] = pd.to_numeric(
        metadata["diameter_1"],
        errors="coerce",
    )

    metadata["diameter_2"] = pd.to_numeric(
        metadata["diameter_2"],
        errors="coerce",
    )

    metadata["hurt"] = normalize_bool(
        metadata["hurt"]
    )

    # The metadata contains one row per image.
    # Collapse to one clinical record per lesion.
    grouped = []

    for (
        patient_id,
        lesion_id_key,
    ), group in metadata.groupby(
        [
            "patient_id",
            "lesion_id_key",
        ],
        sort=False,
    ):
        grouped.append(
            {
                "patient_id": patient_id,
                "lesion_id_key": lesion_id_key,
                "diameter_1": group[
                    "diameter_1"
                ].dropna().iloc[0]
                if group["diameter_1"].notna().any()
                else np.nan,
                "diameter_2": group[
                    "diameter_2"
                ].dropna().iloc[0]
                if group["diameter_2"].notna().any()
                else np.nan,
                "hurt": (
                    group["hurt"]
                    .dropna()
                    .iloc[0]
                    if group["hurt"].notna().any()
                    else np.nan
                ),
            }
        )

    return pd.DataFrame(grouped)


def merge_geometry_metadata(
    geometry,
    metadata,
    label,
):
    merged = geometry.merge(
        metadata,
        on=[
            "patient_id",
            "lesion_id_key",
        ],
        how="left",
        validate="one_to_one",
        indicator=True,
    )

    missing = merged[
        merged["_merge"] != "both"
    ]

    if len(missing) > 0:
        raise RuntimeError(
            f"{label}: metadata missing for "
            f"{len(missing)} lesions:\n"
            + missing[
                [
                    "patient_id",
                    "lesion_uid",
                ]
            ].to_string(index=False)
        )

    merged = merged.drop(
        columns="_merge"
    )

    merged["lesion_area_proxy"] = (
        merged["diameter_1"]
        * merged["diameter_2"]
    )

    merged["size_d1_group"] = np.where(
        merged["diameter_1"]
        <= merged["diameter_1"].median(),
        "small_or_equal",
        "large",
    )

    merged["size_d2_group"] = np.where(
        merged["diameter_2"]
        <= merged["diameter_2"].median(),
        "small_or_equal",
        "large",
    )

    merged["area_size_group"] = np.where(
        merged["lesion_area_proxy"]
        <= merged["lesion_area_proxy"].median(),
        "small_or_equal",
        "large",
    )

    merged["error_group"] = np.where(
        merged["error_fraction"] > 0,
        "problematic",
        "clean",
    )

    return merged


def safe_mann_whitney(
    a,
    b,
):
    a = np.asarray(a, dtype=float)
    b = np.asarray(b, dtype=float)

    a = a[np.isfinite(a)]
    b = b[np.isfinite(b)]

    if len(a) == 0 or len(b) == 0:
        return np.nan

    return float(
        mannwhitneyu(
            a,
            b,
            alternative="two-sided",
        ).pvalue
    )


def print_group_summary(
    df,
    group_name,
):
    print()
    print(
        f"GROUP: {group_name}"
    )
    print("-" * 70)

    print(
        f"N lesions:              {len(df)}"
    )

    problematic = (
        df["error_group"]
        == "problematic"
    )

    print(
        f"Problematic:            "
        f"{problematic.sum()}"
    )

    print(
        f"Clean:                  "
        f"{(~problematic).sum()}"
    )

    hurt = df["hurt"] == True

    print(
        f"Hurt=True:              "
        f"{hurt.sum()}"
    )

    print(
        f"Hurt=False:             "
        f"{(~hurt).sum()}"
    )

    print(
        f"Problematic & hurt:     "
        f"{(problematic & hurt).sum()}"
    )

    print(
        f"Problematic & not hurt: "
        f"{(problematic & ~hurt).sum()}"
    )

    print(
        f"Clean & hurt:           "
        f"{((~problematic) & hurt).sum()}"
    )

    print(
        f"Clean & not hurt:       "
        f"{((~problematic) & ~hurt).sum()}"
    )


def analyze_hurt_effect(
    df,
    label,
):
    print()
    print("=" * 80)
    print(
        f"{label}: HURT × ERROR GEOMETRY"
    )
    print("=" * 80)

    hurt = df[
        df["hurt"] == True
    ]

    not_hurt = df[
        df["hurt"] == False
    ]

    for subset_name, subset in [
        ("HURT", hurt),
        ("NOT HURT", not_hurt),
    ]:
        problematic = subset[
            subset["error_group"]
            == "problematic"
        ]

        clean = subset[
            subset["error_group"]
            == "clean"
        ]

        print()
        print(subset_name)
        print("-" * 70)

        print(
            f"Total:       {len(subset)}"
        )

        print(
            f"Problematic: {len(problematic)}"
        )

        print(
            f"Clean:       {len(clean)}"
        )

        if len(problematic) > 0:
            print(
                f"Problematic fraction: "
                f"{len(problematic) / len(subset):.4f}"
            )

        if (
            len(problematic) > 0
            and len(clean) > 0
        ):
            print(
                f"Mean margin problematic: "
                f"{problematic['bcc_minus_scc_distance'].mean():.6f}"
            )

            print(
                f"Mean margin clean:       "
                f"{clean['bcc_minus_scc_distance'].mean():.6f}"
            )

            p_value = safe_mann_whitney(
                problematic[
                    "bcc_minus_scc_distance"
                ],
                clean[
                    "bcc_minus_scc_distance"
                ],
            )

            print(
                f"Mann-Whitney p: "
                f"{p_value:.6f}"
            )


def analyze_size_within_hurt(
    df,
    label,
):
    print()
    print("=" * 80)
    print(
        f"{label}: SIZE × HURT × ERROR"
    )
    print("=" * 80)

    for size_column, display_name in [
        (
            "diameter_1",
            "diameter_1",
        ),
        (
            "diameter_2",
            "diameter_2",
        ),
        (
            "lesion_area_proxy",
            "lesion_area_proxy",
        ),
    ]:
        threshold = df[
            size_column
        ].median()

        print()
        print(
            f"SIZE VARIABLE: {display_name}"
        )
        print(
            f"Median threshold: "
            f"{threshold:.4f}"
        )

        size_group = np.where(
            df[size_column]
            <= threshold,
            "small_or_equal",
            "large",
        )

        working = df.copy()
        working["_size_group"] = (
            size_group
        )

        for size_name in [
            "small_or_equal",
            "large",
        ]:
            print()
            print(
                f"  {size_name}"
            )

            part = working[
                working["_size_group"]
                == size_name
            ]

            for hurt_value in [
                True,
                False,
            ]:
                hurt_part = part[
                    part["hurt"]
                    == hurt_value
                ]

                problematic = (
                    hurt_part[
                        hurt_part[
                            "error_group"
                        ]
                        == "problematic"
                    ]
                )

                clean = (
                    hurt_part[
                        hurt_part[
                            "error_group"
                        ]
                        == "clean"
                    ]
                )

                print(
                    f"    hurt={hurt_value}: "
                    f"n={len(hurt_part):2d} "
                    f"problematic="
                    f"{len(problematic):2d} "
                    f"clean="
                    f"{len(clean):2d}"
                )

                if len(hurt_part) > 0:
                    print(
                        f"      problematic "
                        f"fraction="
                        f"{len(problematic) / len(hurt_part):.4f}"
                    )

                if (
                    len(problematic) > 0
                    and len(clean) > 0
                ):
                    print(
                        f"      problematic "
                        f"margin="
                        f"{problematic['bcc_minus_scc_distance'].mean():.6f}"
                    )

                    print(
                        f"      clean margin="
                        f"{clean['bcc_minus_scc_distance'].mean():.6f}"
                    )

                    p_value = safe_mann_whitney(
                        problematic[
                            "bcc_minus_scc_distance"
                        ],
                        clean[
                            "bcc_minus_scc_distance"
                        ],
                    )

                    print(
                        f"Mann-Whitney p: "
                        f"{p_value:.6f}"
                    )


def analyze_hurt_size_distribution(
    df,
    label,
):
    print()
    print("=" * 80)
    print(
        f"{label}: HURT × SIZE DISTRIBUTION"
    )
    print("=" * 80)

    for hurt_value in [
        True,
        False,
    ]:
        subset = df[
            df["hurt"] == hurt_value
        ]

        print()
        print(
            f"hurt={hurt_value}"
        )
        print("-" * 70)

        if len(subset) == 0:
            print("No observations.")
            continue

        for column in [
            "diameter_1",
            "diameter_2",
            "lesion_area_proxy",
        ]:
            print(
                f"{column}: "
                f"n={subset[column].notna().sum()} "
                f"mean={subset[column].mean():.4f} "
                f"median={subset[column].median():.4f}"
            )


def save_outputs(
    combined,
):
    OUTPUT_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    combined_path = (
        OUTPUT_DIR
        / "hurt_size_geometry_lesions.csv"
    )

    combined.to_csv(
        combined_path,
        index=False,
    )

    summary_path = (
        OUTPUT_DIR
        / "summary.txt"
    )

    with summary_path.open(
        "w",
        encoding="utf-8",
    ) as handle:
        handle.write(
            "DERMASENSE SCC HURT × SIZE × "
            "GEOMETRY AUDIT\n"
        )
        handle.write(
            "=" * 80 + "\n\n"
        )

        for label in [
            "C1",
            "F1",
        ]:
            df = combined[
                combined["model"]
                == label
            ]

            handle.write(
                f"{label}\n"
            )
            handle.write(
                "-" * 40 + "\n"
            )

            for hurt_value in [
                True,
                False,
            ]:
                subset = df[
                    df["hurt"]
                    == hurt_value
                ]

                problematic = (
                    subset[
                        subset["error_group"]
                        == "problematic"
                    ]
                )

                handle.write(
                    f"hurt={hurt_value}: "
                    f"n={len(subset)}, "
                    f"problematic="
                    f"{len(problematic)}, "
                    f"clean="
                    f"{len(subset) - len(problematic)}\n"
                )

            handle.write("\n")

    print()
    print("=" * 80)
    print("SAVED")
    print("=" * 80)
    print(
        f"Lesion table: {combined_path}"
    )
    print(
        f"Summary:      {summary_path}"
    )


def main():
    print("=" * 80)
    print(
        "DERMASENSE SCC HURT × SIZE × "
        "GEOMETRY AUDIT"
    )
    print("=" * 80)

    metadata = load_metadata()

    print()
    print(
        f"Clinical metadata lesions: "
        f"{len(metadata)}"
    )

    all_results = []

    for label, path in GEOMETRY_PATHS.items():
        geometry = load_geometry(
            path,
            label,
        )

        merged = merge_geometry_metadata(
            geometry,
            metadata,
            label,
        )

        print()
        print(
            f"{label}: matched lesions = "
            f"{len(merged)}"
        )

        if len(merged) != 22:
            raise RuntimeError(
                f"{label}: expected 22 SCC "
                f"lesions, got {len(merged)}"
            )

        if merged["hurt"].isna().any():
            raise RuntimeError(
                f"{label}: missing hurt values."
            )

        merged["model"] = label

        print_group_summary(
            merged,
            label,
        )

        analyze_hurt_effect(
            merged,
            label,
        )

        analyze_size_within_hurt(
            merged,
            label,
        )

        analyze_hurt_size_distribution(
            merged,
            label,
        )

        all_results.append(
            merged
        )

    combined = pd.concat(
        all_results,
        ignore_index=True,
    )

    save_outputs(
        combined
    )

    print()
    print("=" * 80)
    print(
        "HURT × SIZE × GEOMETRY AUDIT COMPLETE"
    )
    print("=" * 80)


if __name__ == "__main__":
    main()
